version: '3.8'

x-hub: &HUB
  build:
    context: ./docker/echo-server
    dockerfile: Dockerfile
  command: npm start
  restart: always
  env_file: .env


services:
  proxy:
    build:
      context: ./
      dockerfile: Dockerfile
    command: npm start
    restart: always
    env_file: .env
    volumes:
      - ./certs/:/opt/app/certs/
    ports:
      - "${HTTP_PORT_A}:${HTTP_PORT_A}"
      - "${HTTP_PORT_B}:${HTTP_PORT_A}"

  hub-a:
    <<: *HUB
    ports:
      - "${HUB_A_PORT}:6000"

  hub-b:
    <<: *HUB
    ports:
      - "${HUB_B_PORT}:6000"
