name: 'get-npm-cache Action'
description: 'Retrieve and restore NPM cache'

outputs:
  cache-dir:
    value: ${{ steps.npm-cache-dir.outputs.cache-dir }}
    description: 'NPM cache directory'

runs:
  using: 'composite'

  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Get npm-cache directory
      id: npm-cache-dir
      shell: bash
      run: |
        echo "cache-dir=$(npm config get cache)" >> $GITHUB_OUTPUT
      # by default, it should be ~/.npm

    - name: Restore npm cache
      id: npm-cache-restore
      uses: actions/cache/restore@v4
      with:
        path: ${{ steps.npm-cache-dir.outputs.cache-dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    # todo: think, if we should move npm ci here?
